apiVersion: v1
kind: Pod
metadata:
  name: postgress
  labels:
    name: postgress
    tier: database
    app: demo-voting-app
spec:
  containers:
  - name: postgree
    image: postgres
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"
