apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    name: result-app
    tier: frontend
    app: demo-voting-app
spec:
  containers:
  - name: result-app-js
    image: kodekloud/examplevotingapp_result:v1
    ports:
      - containerPort: 80
